### ISSUE TITLE
Create instructions screen

### ISSUE THREAD

**Issue by jahnnah-ray** [dianaixta/Productivity-Tracker#1]

**Comment by jahnnah-ray** [comment]
Screen wont stay open

**Comment by ccurtis7** [comment]
I believe this is resolved, right? Is this related to the problem you described to me today? You were having problems launching the main screen after you click on the "Let's Begin" button on the instruction screen.

We resolved this issue with the following code:

https://github.com/dianaixta/Productivity-Tracker/blob/20d3da71071012f1bc04b502ee70f037868ecbb3/instructscreen.py#L43-L54

The main issues were two-fold:
1. You were calling on the `getButton` method twice in each if statement, rather than grabbing the output once and
2. You were treating the output of `getButton` as a Boolean instead of a string.

Once we fixed these, it worked as expected.

**Comment by jahnnah-ray** [comment]
Fixed
